INSERT INTO user_table (username, password, role) VALUES
('user','$2a$10$NVM0n8ElaRgg7zWO1CxUdei7vWoPg91Lz2aYavh9.f9q0e4bRadue','USER'),
('admin','$2a$10$8cjz47bjbR4Mn8GMg9IZx.vyjhLXR/SKKMSZ9.mP9vpMu0ssKi8GW','ADMIN');

INSERT INTO actors (name, age, portrait, about) VALUES
('Brad Pitt', 59, 'https://media.gettyimages.com/id/1200624305/photo/los-angeles-california-brad-pitt-winner-outstanding-performance-by-a-male-actor-in-a.jpg?s=612x612&w=0&k=20&c=nmrZxUOwJhfwjzfDRWMOZWvkQl-Wg6K4XO89GnWJqlk=', 'William Bradley Pitt is an American actor and film producer. He is the recipient of various accolades, including two Academy Awards, a British Academy Film Award, two Golden Globe Awards, and a Primetime Emmy Award.'),
('Chris Pratt', 44, 'https://media.gettyimages.com/id/452657110/photo/london-united-kingdom-chris-pratt-attends-the-guardians-of-the-galacy-photocall-on-july-25.jpg?s=612x612&w=0&k=20&c=d3ORzrPY-pBgZ5YR1aHgwwmGpQhr48HiiMA0g60FXBo=', 'Christopher Michael Pratt is an American actor. He rose to prominence for playing Andy Dwyer in the NBC sitcom Parks and Recreation. He also appeared in The WB drama series Everwood and had supporting roles in the films Wanted, Jennifer''s Body, Moneyball, Zero Dark Thirty, and Her.'),
('Jaime Foxx', 55, 'https://media.gettyimages.com/id/1197977174/photo/los-angeles-california-jamie-foxx-attends-the-la-community-screening-of-warner-bros-pictures.jpg?s=612x612&w=0&k=20&c=zqIPz5a62rtbl-TZWcS2nQz6UNiJ434JJCqTCUNM5xU=', 'Eric Marlon Bishop, known professionally as Jamie Foxx, is an American actor, comedian, and singer. He became widely known for his portrayal of Ray Charles in the 2004 biographical film Ray, for which he won the Academy Award, BAFTA, Screen Actors Guild Award, Critics'' Choice Movie Award and Golden Globe Award for Best Actor.'),
('Tom Hardy', 46, 'https://media.gettyimages.com/id/505034362/photo/london-england-tom-hardy-attends-uk-premiere-of-the-revenant-at-empire-leicester-square-on.jpg?s=612x612&w=0&k=20&c=Q0jcEXfZvPiR6eg-mEL_7fZ9J1VaNlhJkP-WvMnCYyU=', 'Edward Thomas Hardy CBE is an English actor. After studying acting at the Drama Centre London, he made his film debut in Ridley Scott''s Black Hawk Down.'),
('Ryan Reynolds', 47, 'https://media.gettyimages.com/id/1373905219/photo/new-york-new-york-ryan-reynolds-attends-the-adam-project-new-york-premiere-on-february-28.jpg?s=612x612&w=0&k=20&c=AbUbh7EkIySZJi3hgHkJPvqAqWYAIyqmu2ySETBIDPY=', 'Ryan Rodney Reynolds started out in television before becoming a big-screen success in Hollywood. His first major breakthrough came with the 2002 comedy National Lampoon''s Van Wilder. Since then, Reynolds has become known for his starring role in Deadpool.'),
('Benedict Cumberbatch', 48, 'https://media.gettyimages.com/id/459534806/photo/los-angeles-ca-actor-benedict-cumberbatch-arrives-at-the-los-angeles-special-screening-of-the.jpg?s=612x612&w=0&k=20&c=dMtsFqNyhog1rooTTCzvVcRfTvmMDRWHpG7MPk1ZxKM=', 'Benedict Timothy Carlton Cumberbatch CBE is an English actor. Known for his work on screen and stage, he has received various accolades, including a British Academy Television Award, a Primetime Emmy Award and a Laurence Olivier Award.'),
('Sam Worthington', 47, 'https://media.gettyimages.com/id/1448720583/photo/hollywood-california-sam-worthington-attends-20th-century-studios-avatar-2-the-way-of-water-u.jpg?s=612x612&w=0&k=20&c=gld901h1lVJk-uL1UUGXdXEnUbcwxrcnV_nvIjV__sE=', 'Samuel Henry John Worthington is an Australian actor. He is best known for playing Jake Sully in Avatar, Marcus Wright in Terminator Salvation, and Perseus in Clash of the Titans and its sequel Wrath of the Titans.'),
('Hugh Jackman', 55, 'https://media.gettyimages.com/id/86275261/photo/los-angeles-ca-actor-hugh-jackman-arrives-at-the-screening-20th-century-foxs-x-men-origins.jpg?s=612x612&w=0&k=20&c=EvwUwLl7OqWIn3m6nJe7wVjvPxJNoN4YKy4oE_KbG-o=', 'Australian actor and producer Hugh Jackman is best known for playing Wolverine in the ''X-Men'' film franchise. He''s also known for parts in musicals such as ''Les Misérables'' and ''The Greatest Showman.'''),
('Leonardo DiCaprio', 49, 'https://media.gettyimages.com/id/1205143953/photo/hollywood-california-leonardo-dicaprio-attends-the-92nd-annual-academy-awards-at-hollywood.jpg?s=612x612&w=0&k=20&c=Dfn_piD3_bXdyf19tUhWJS--QIpi-DzO9CAu2VMfBrY=', 'American actor and producer Leonardo DiCaprio has had a varied career, starring in movies from ''Titanic'' to ''The Revenant.'' His role in ''The Revenant'' won him his first Oscar.'),
('Dwayne Johnson', 51, 'https://media.gettyimages.com/id/944934900/photo/london-england-dwayne-johnson-attends-the-european-premiere-of-rampage-at-cineworld-leicester.jpg?s=612x612&w=0&k=20&c=W5ifVpJKTZLNuyNs-VJc3VG4WugkUARop0d8bnsmknA=', 'Dwayne "The Rock" Johnson first rose to fame as a wrestler in the WWE before becoming a Hollywood star. He''s known for movies like ''The Scorpion King,'' ''Hercules,'' and the ''Fast & Furious'' series.'),
('Henry Cavill', 40, 'https://media.gettyimages.com/id/1437117381/photo/new-york-new-york-henry-cavill-attends-netflixs-enola-holmes-2-world-premiere-at-the-paris.jpg?s=612x612&w=0&k=20&c=rcyXdbGhsqzSKo3NqZo1YCxUo2_fviSOvbUEYzIvJPk=', 'After landing his first film role as a teenager, Henry Cavill began pursuing his acting ambitions on the British screen. He enjoyed a breakout role in Showtime''s "The Tudors" from 2007-10 before shooting to stardom as Superman in 2013''s Man of Steel. Cavill also showcased his action chops in The Man from U.N.C.L.E. (2015) and Mission: Impossible–Fallout (2018) before headlining the Netflix fantasy series "The Witcher" beginning in 2019.'),
('Robert Downey Jr.', 58, 'https://media.gettyimages.com/id/803015182/photo/hollywood-ca-robert-downey-jr-attends-the-premiere-of-columbia-pictures-spider-man-homecoming.jpg?s=612x612&w=0&k=20&c=NoC3-N2l-Q3pFtjlgOW0xa4kbrqZvf0qtuGcHA4T4vA=', 'Born in New York City, Robert Downey Jr. began acting as a young child. He made his first film appearances and was a cast member on Saturday Night Live in the 1980s, but his growing success was marred by years of struggles with drug abuse. Eventually turning his life around, he earned a resurgence of critical and popular acclaim. He is known for roles in a wide variety of films, including ''Iron Man,'' ''The Avengers, ''Sherlock Holmes'' and ''Chaplin.'''),
('Ben Stiller', 57, 'https://media.gettyimages.com/id/1090372712/photo/west-hollywood-california-actor-ben-stiller-attends-the-showtime-golden-globe-nominees.jpg?s=612x612&w=0&k=20&c=hwOOUgv7QbsxdL8fDd98TMKmKzjDvEJW_mVC3jcy2dk=', 'The son of comedians Jerry Stiller and Anne Meara, Ben Stiller grew up in New York City. Early in his career, he wrote for Saturday Night Live and created the short-lived The Ben Stiller Show. After directing and starring in several movies, he earned widespread fame for the 1998 gross-out comedy There''s Something About Mary. Stiller has since starred in Zoolander, as well as the successful Meet the Parents and Night at the Museum films.'),
('Chris Evans', 42, 'https://media.gettyimages.com/id/478558797/photo/hollywood-ca-chris-evans-arrives-at-the-los-angeles-premiere-of-captain-america-the-winter.jpg?s=612x612&w=0&k=20&c=zz__sLN6nrDwr922bM71ZbIp5igqnkNWZSOh5i9c_Qg=', 'Born and raised in the Boston area, Chris Evans landed his first major film role in the spoof Not Another Teen Movie. He played the Human Torch in two Fantastic Four flicks, but it was his turn as another superhero that propelled him to fame in the enormously successful Captain America and The Avengers blockbusters. Evans also earned acclaim for his performance in the dystopian Snowpiercer and made a well-received Broadway debut in 2018.'),
('Adam Sandler', 57, 'https://media.gettyimages.com/id/1191563950/photo/new-york-new-york-adam-sandler-attends-the-2019-ifp-gotham-awards-at-cipriani-wall-street-on.jpg?s=612x612&w=0&k=20&c=oroc73S6hUgq2-3AlQmEVrH1NtU9eugtNOCQJqx_vqs=', 'Born in New York City, Adam Sandler was always the class clown but didn''t consider becoming a comedian until his brother encouraged him to perform at a Boston Comedy Club. He was a regular on MTV''s Remote Control and on NBC''s Saturday Night Live before devoting himself to making movies like Billy Madison and Happy Gilmore. Sandler is best known for comedy but has also received critical praise for his dramatic work.'),
('Chris Hemsworth', 40, 'https://media.gettyimages.com/id/1442079658/photo/new-york-new-york-chris-hemsworth-attends-national-geographics-limitless-screening-and.jpg?s=612x612&w=0&k=20&c=h98oL0t3USwqbZHD8_ljhzqaWpMAenTberBPKOwU2bg=', 'Australian heartthrob Chris Hemsworth has made quite a name for himself by swinging his hammer as Marvel comic book character Thor, starring in several films under that title and in related features like The Avengers. The Melbourne native and married dad has also earned leading roles in Snow White and the Huntsman, Rush and In the Heart of the Sea, while showing his comedic chops in reboots of Vacation and Ghostbusters.'),
('Samuel L. Jackson', 74, 'https://media.gettyimages.com/id/1158541037/photo/hollywood-california-samuel-l-jackson-attends-the-premiere-of-sony-pictures-spider-man-far.jpg?s=612x612&w=0&k=20&c=89AHpeTGU_aeEASrshUo7jgoWoY8o3l_CNEbjbbXgRQ=', 'Samuel L. Jackson graduated from Morehouse College in 1972 and began his acting career on stage. A move to New York City led to a friendship with Spike Lee and some of his first movie gigs before he enjoyed a star-making turn with a commanding performance in Pulp Fiction. Jackson became a ubiquitous presence on the big screen, appearing in big-budget films like Star Wars: The Phantom Menace and its sequels, and the numerous installments of the Marvel Cinematic Universe.'),
('Will Smith', 55, 'https://media.gettyimages.com/id/464337244/photo/hollywood-ca-actor-will-smith-attends-the-warner-bros-pictures-focus-premiere-at-tcl-chinese.jpg?s=612x612&w=0&k=20&c=86Vl-9eLe8yihOXxJGdYQuxXFLArqj7tkTxH0mO9EJ4=', 'Willard Carroll "Will" Smith II is an American actor, comedian, producer, rapper, and songwriter. He has enjoyed success in television, film, and music. In April 2007, Newsweek called him "the most powerful actor in Hollywood". Smith has been nominated for five Golden Globe Awards, two Academy Awards, and has won four Grammy Awards.In the late 1980s, Smith achieved modest fame as a rapper under the name The Fresh Prince. In 1990, his popularity increased dramatically when he starred in the popular television series The Fresh Prince of Bel-Air.'),
('Johnny Depp', 60, 'https://media.gettyimages.com/id/684952360/photo/hollywood-ca-actor-johnny-depp-attends-the-premiere-of-disneys-pirates-of-the-caribbean-dead.jpg?s=612x612&w=0&k=20&c=2a55CFBl9Tos5jHwBSnyWluR_bK5y7SOGYc67pnuNeU=', 'Johnny Depp landed his first legitimate movie role in Nightmare on Elm Street (1984). He began studying acting in earnest, the lessons paying off in 1987 when he landed a role on the TV show 21 Jump Street. He has since become known for his willingness to take on darker roles in films such as Edward Scissorhands (1990), Sleepy Hollow (1999) and Alice in Wonderland (2010), as well as his starring efforts in the big-budget Pirates of the Caribbean movies.'),
('Denzel Washington', 68, 'https://media.gettyimages.com/id/1154310819/photo/hollywood-california-honoree-denzel-washington-speaks-onstage-during-the-47th-afi-life.jpg?s=612x612&w=0&k=20&c=W7aFjLaRKlNBqyc2Tx6kGHTEgdEf0bw2Q-bLfGvY0Jo=', 'Denzel Washington first studied journalism at Fordham University but then discovered an interest in acting. He made his feature film debut in the comedy A Carbon Copy (1981) and was cast on the hit TV medical drama St. Elsewhere (1982-88). He went on to appear in several hit movies, including Philadelphia, Man on Fire, The Book of Eli, American Gangster and Flight, and won Oscars for his roles in Glory and Training Day. He received an Oscar nomination for his starring role in 2016''s Fences, an adaptation of August Wilson''s Tony and Pulitzer Prize-winning play, and for the 2017 film Roman J. Israel, Esq.'),
('Tom Hanks', 67, 'https://media.gettyimages.com/id/632013890/photo/los-angeles-ca-actor-tom-hanks-attends-the-peoples-choice-awards-2017-at-microsoft-theater-on.jpg?s=612x612&w=0&k=20&c=I1gYAfYz05PfsAJxb57f6Z55j24fQmljty4CTmqGPZM=', 'Tom Hanks began performing with the Great Lakes Shakespeare Festival in 1977, later moving to New York City. He starred in the television sitcom Bosom Buddies, but became far more known when he starred in the Ron Howard film Splash. He went on to headline many more popular and acclaimed movies, including Big, Forrest Gump and Cast Away, en route to becoming one of the most powerful and well-respected actors in Hollywood.'),
('Chadwick Boseman', 44, 'https://media.gettyimages.com/id/915847344/photo/london-england-chadwick-boseman-attends-the-european-premiere-of-marvel-studios-black-panther.jpg?s=612x612&w=0&k=20&c=DjNq1ZTNfItVqY6CQX1RIHZjowdQkC6LwmeIYwr12xo=', 'Chadwick Boseman had early success as a stage actor, writer and director, before landing gigs on TV shows like Lincoln Heights. Boseman broke through with his big screen portrayals of two African American icons: baseball player Jackie Robinson in 42, and soul singer James Brown in Get on Up. Boseman later took on the role of Black Panther for a series of Marvel superhero films, including the immensely successful Black Panther in early 2018.'),
('Tom Cruise', 61, 'https://media.gettyimages.com/id/693134382/photo/new-york-ny-tom-cruise-attends-the-the-mummy-new-york-fan-eventat-amc-loews-lincoln-square-on.jpg?s=612x612&w=0&k=20&c=lh5UoYn4SrCLmzsZ7FsZQjlMM8oE8IUkHMpSfELBJjA=', 'Tom Cruise is an American actor known for his roles in iconic films throughout the 1980s, 1990s and 2000s, as well as his high profile marriages to actresses Nicole Kidman and Katie Holmes. After developing an interest in acting during high school, he rocketed to fame with his star turns in Risky Business and Top Gun. Cruise later earned acclaim for his work in the hit film Jerry Maguire and the Mission: Impossible franchise.'),
('Zac Efron', 36, 'https://media.gettyimages.com/id/1089877744/photo/park-city-ut-zac-efron-of-extremely-wicked-shockingly-evil-and-vile-attends-the-imdb-studio.jpg?s=612x612&w=0&k=20&c=DafwB0Md6X7ZecSSEoYQJHGXUJCRJ2MB8VCuPWDmhPU=', 'Zac Efron made his first television appearance on the series Firefly. In 2005, Efron landed the lead role in the Disney Channel film High School Musical, which proved a massive hit and spawned two sequels. He went on to star in a remake of Hairspray and voice the main character in The Lorax, before dropping his Disney image and taking on more mature roles in films such as The Lucky One and Parkland. Efron later starred in Neighbors, Dirty Grandpa, the P.T. Barnum biopic The Greatest Showman and as serial killer Ted Bundy in Extremely Wicked, Shockingly Evil and Vile.');
